# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JlWR5bAPH_wk8tIwd-J-NVj_g5-cBSpm

# Calculadora Python
"""

print("\n****************Calculadora Python****************")

def Soma(x, y):
    Resultado = x + y
    return print(Resultado)

def Subtração(x, y):
    Resultado = x - y
    return print(Resultado)

def Multiplicação(x, y):
    Resultado = x * y
    return print(Resultado)

def Divisão(x, y):
    Resultado = x / y
    return print(Resultado)

print("\nEscolha a operação desejada:\n")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")

Operação = input("Digite o nº da operação desejada (1, 2, 3 ou 4):")
x = float(input("Primeiro nº:"))
y = float(input("Segundo nº: "))

if Operação == '1':
    Soma(x,y)
elif Operação == '2':
    Subtração(x,y)
elif Operação == '3':
    Multiplicação(x,y)
elif Operação == '4':
    Divisão(x,y)
else:
    print("Operação inválida")